<?php
/**
 * @file Drupal's settings.php file
 *
 * This file was automatically generated by Aegir 6.x-2.x
 * on Sat, 20 Feb 2016 15:08:03 +0000.
 *
 * If it is still managed by Aegir, changes to this file may be
 * lost. If it is not managed by aegir, you should remove this header
 * to avoid further confusion.
 */


  $databases['default']['default'] = array(
    'driver' => "mysqli",
    'database' => "heaven",
    'username' => "root",
    'password' => "mojah42",
    'host' => "db",
    'port' => "3306",
   );
 #$db_url['default'] = "mysqli://heaven2devdo22mf:KVsPFL8aod@localhost:3306/heaven2devdo22mf";
  $db_url = 'mysql://root:mojah42@db/heaven';

  $profile = "default";
  $install_profile = "default";

  /**
  * PHP settings:
  *
  * To see what PHP settings are possible, including whether they can
  * be set at runtime (ie., when ini_set() occurs), read the PHP
  * documentation at http://www.php.net/manual/en/ini.php#ini.list
  * and take a look at the .htaccess file to see which non-runtime
  * settings are used there. Settings defined here should not be
  * duplicated there so as to avoid conflict issues.
  */
  @ini_set('arg_separator.output',     '&amp;');
  @ini_set('magic_quotes_runtime',     0);
  @ini_set('magic_quotes_sybase',      0);
  @ini_set('session.cache_limiter',    'none');
  @ini_set('session.save_handler',     'user');
  @ini_set('session.use_cookies',      1);
  @ini_set('session.use_only_cookies', 1);
  @ini_set('session.use_trans_sid',    0);
  @ini_set('url_rewriter.tags',        '');

  /**
  * Set the umask so that new directories created by Drupal have the correct permissions
  */
  umask(0002);


  global $conf;
  $conf['install_profile'] = 'default';
  $conf['file_directory_path'] = 'sites/heavenletters.org/files';
  $conf['file_directory_temp'] = 'sites/heavenletters.org/private/temp';
  $conf['clean_url'] = 1;
  $conf['aegir_api'] = 2;


# Extra configuration from modules:

  # Additional host wide configuration settings. Useful for safely specifying configuration settings.
  if (file_exists('/var/aegir/config/includes/global.inc')) {
    include_once('/var/aegir/config/includes/global.inc');
  }

  # Additional site configuration settings.
  if (file_exists('/var/aegir/platforms/drupal-5.x-dev/sites/heavenletters.org/local.settings.php')) {
    include_once('/var/aegir/platforms/drupal-5.x-dev/sites/heavenletters.org/local.settings.php');
  }
